# Generated by Django 3.2.20 on 2023-07-12 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0027_auto_20230504_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='claps',
            field=models.ManyToManyField(blank=True, default=None, related_name='claps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='loves',
            field=models.ManyToManyField(blank=True, default=None, related_name='loves', to=settings.AUTH_USER_MODEL),
        ),
    ]
