# Generated by Django 3.2.20 on 2023-09-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autentikasi', '0005_auto_20230506_1115'),
        ('post', '0029_initialpost_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialpost',
            name='seen',
            field=models.ManyToManyField(blank=True, default=None, related_name='seen', to='autentikasi.CustomUser'),
        ),
    ]
