# Generated by Django 3.2.20 on 2023-09-20 06:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0030_alter_initialpost_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialpost',
            name='seen',
            field=models.ManyToManyField(blank=True, default=None, related_name='seen', to=settings.AUTH_USER_MODEL),
        ),
    ]
