# Generated by Django 3.2.20 on 2023-07-12 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20230315_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='thread',
        ),
        migrations.AddField(
            model_name='thread',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 12, 17, 48, 59, 223625)),
        ),
        migrations.AddField(
            model_name='thread',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='mechanism_expectation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='state',
            field=models.CharField(choices=[('1', 'Phase1'), ('2', 'Phase2'), ('3', 'Phase3'), ('4', 'Phase4'), ('5', 'Phase5')], default='1', max_length=255),
        ),
        migrations.AddField(
            model_name='thread',
            name='summary_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='referencefile',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='DiscussionGuide',
        ),
        migrations.DeleteModel(
            name='Summary',
        ),
    ]
