# Generated by Django 3.2.20 on 2023-07-12 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20230712_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 13, 1, 34, 13, 829022)),
        ),
    ]
