# Generated by Django 3.2.20 on 2023-09-20 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0017_alter_thread_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 20, 15, 46, 8, 469428)),
        ),
    ]
