# Generated by Django 3.2.20 on 2023-09-21 10:44

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0025_auto_20230920_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='user_done',
            field=models.ManyToManyField(blank=True, default=None, related_name='user_done', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thread',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 21, 17, 44, 14, 447940)),
        ),
    ]
