# Generated by Django 3.2.20 on 2023-12-05 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0026_auto_20230921_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 5, 17, 41, 49, 363785)),
        ),
    ]
